services:
  - type: web
    plan: free
    name: Flash
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m FlashXMusic
    repo: https://github.com/Zenaku2050s/ZenakuRobot      
    branch: master
    envVars:
      - key: SUDO_USERS 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: STRING_SESSION1
        sync: false
      - key: MONGO_URL
        sync: false    
    autoDeploy: false
